### ISSUE TITLE
Downloaded app is not installed. Getting error "App not Installed".

### ISSUE THREAD

**Issue by neethuantony42** [Piashsarker/AndroidAppUpdateLibrary#6]
Hi @Piashsarker ,
I have used the code  to download and install the app but  I am getting an error "App not Installed".
Could you please help me on this?
App url I have used is "https://github.com/neethuantony42/SampleAutoUpdateapk/raw/master/appdebug.apk".

Thanks and Regards,
Neethu Antony

**Comment by cyb3rko** [comment]
Did you try it on Android 10? Because with Android 10 the old installing process is deprecated and does not work anymore.

**Comment by Piashsarker** [comment]
I have to update this library for Android 10.  Will try to get to you soon.

**Comment by cyb3rko** [comment]
Would be awesome, I really want this feature in my projects.
I can try to work on it as well.

**Comment by Piashsarker** [comment]
Yes, you can do that. Clone this project and make a PR.

**Comment by cyb3rko** [comment]
Yep, let's see if I can do it

**Comment by cyb3rko** [comment]
@neethuantony42 Btw "App not installed" is also shown if you try to update an app with a different build variant than the currently installed.

@Piashsarker Is the apk file in this repo here a release or debug build? Because if it's a debug build the update should work, but it does not (also not for me).

**Comment by Piashsarker** [comment]
@cyb3rko  it's a debug build, Are you facing problem with signed apk ?

**Comment by cyb3rko** [comment]
It thought it would be the problem but if both APKs are debug builds, this is not the problem.

I think I figured it out now:
Because the APK that gets downloaded has the same version code / name it fails.
I just built a new APK with another version, now it works. Should I make a pull request for uploading a new APK?

**Comment by cyb3rko** [comment]
@Piashsarker I suppose you missed my message above.
